# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to retrieve battlegrounds aggregated stats

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
        MinimumCompressionSize: 100

Resources:
    GetBgsGlobalStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-bgs-global-stats.default
            Runtime: nodejs10.x
            Timeout: 180
            CodeUri: ./dist/retrieve-bgs-global-stats
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-bgs-global-stats
            Events:
                GetMatchStatsResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    GetBgsGlobalStatsApi:
        Description: URL to retrieve match stats for Firestone users
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
        Export:
            Name: GetBgsGlobalStatsApi
